/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2021-05-15

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stdint.h>
#include "stm32f4xx.h"
#include "rtos.h"

uint32_t ITM_PortSendChar(uint8_t port, uint32_t ch)
{
  if ((ITM->TCR & ITM_TCR_ITMENA_Msk)                  &&      /* ITM enabled */
      (ITM->TER & (1UL << port)        )                    )     /* ITM Port #0 enabled */
  {
    while (ITM->PORT[port].u32 == 0);
    ITM->PORT[port].u8 = (uint8_t) ch;
  }
  return (ch);
}

void ITM_PortPrintf(uint8_t port, char* str, uint32_t length)
{
	if(str != NULL)
	{
		for(int i = 0; i < length - 1; i++)
		{
			ITM_PortSendChar(port, *str);
			str++;
		}
	}
}


void func_1(void)
{
	while(1)
	{
		GPIO_ToggleBits(GPIOG, (1 << 13));
		//ITM_PortPrintf(31, "11", 2UL);
		RTOS_SVC_threadDelay(500);
		//ITM_PortPrintf(31, "12", 2UL);
	}
}

void func_2(void)
{
	while(1)
	{
		GPIO_ToggleBits(GPIOG, (1 << 14));
		RTOS_SVC_threadDelay(1000);
	}
}

RTOS_thread_t thread[2];
RTOS_stack_t stack[2];

int main(void)
{
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOG, ENABLE);
	GPIO_Init(GPIOG, &(GPIO_InitTypeDef){
			(1 << 13) | (1 << 14),
			GPIO_Mode_OUT,
			GPIO_Speed_50MHz,
			GPIO_OType_PP,
			GPIO_PuPd_NOPULL
	  });


	RTOS_init();

	RTOS_SVC_threadCreate(&thread[0], &stack[0], func_1, 1);
	RTOS_SVC_threadCreate(&thread[1], &stack[1], func_2, 1);

	RTOS_SVC_schedulerStart();

	while(1);
}
